name: laundryku
description: "Aplikasi Laundry berbasis Flutter untuk membantu pengelolaan bisnis laudry kecil."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  supabase_flutter: ^2.6.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  timeago: ^3.7.0
  intl: ^0.19.0
  http: ^0.13.0
  google_fonts: ^2.1.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  fl_chart: ^0.66.0

flutter:
  uses-material-design: true
